apiVersion: v1
kind: ConfigMap
metadata:
  name: PLACEHOLDER_APP_NAME-configmap
  namespace: PLACEHOLDER_APP_NAME-PLACEHOLDER_ENVIRONMENT
data:
  ASPNETCORE_ENVIRONMENT: "PLACEHOLDER_ENVIRONMENT"
  AWS_REGION: "PLACEHOLDER_AWS_REGION"
  ASPNETCORE_URLS: "PLACEHOLDER_DEPLOYMENT_ASPNETCORE_URLS"
  ASPNETCORE_ENVIRONMENT: "PLACEHOLDER_DEPLOYMENT_ASPNETCORE_ENVIRONMENT"
