apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: hello-world-api
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: DEBUG
              value: "true"
