apiVersion: v1
kind: Service
metadata:
  name: PLACEHOLDER_APP_NAME-service
  namespace: PLACEHOLDER_APP_NAME-PLACEHOLDER_ENVIRONMENT
spec:
  selector:
    app: PLACEHOLDER_APP_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP