# templates/variables/pix/dev.yaml
# ----------------------------------------------------------------------------
# Variáveis ESPECÍFICAS do domínio PIX — ambiente DEV.
# Mesmos NOMES em dev/hml/prd; só os VALORES mudam (padrão "ambiente é dado").
# ----------------------------------------------------------------------------
variables:
  - name: awsRegion
    value: 'sa-east-1'
  - name: awsAccID
    value: ''
  - name: serviceAccount
    value: 'fibra-pix-dev'
  - name: serviceAccountTerraform
    value: 'fibra-pix-dev'
  - name: clusterName
    value: '-dev'
  - name: albSharedDns
    value: 'interna'
  - name: albSharedListener
    value: 'arn:aws'
  - name: apiGatewayVpcLink
    value: ''
  - name: vpcEndpointApiGateway
    value: 'vpce-'
  - name: domainInternal
    value: 'devr'
  - name: domainInternalID
    value: ''
